export const CLEAR_FORMS = 'CLEAR_FORMS'
export const CREATE_FORM = 'CREATE_FORM'
export const DELETE_FORM = 'DELETE_FORM'
export const FIND_FORMS = 'FIND_FORMS'
export const GET_FORM = 'GET_FORM'
export const REMOVE_FORM = 'REMOVE_FORM'
export const UPDATE_FORM = 'UPDATE_FORM'
